### ISSUE TITLE
RestFul Get 방식중 동적 전달 보단 명시적 DTO를 사용할 수 있도록 변경 요청

### ISSUE THREAD

**Issue by rhkdgur** [f-lab-edu/black-friday#5]
- 원인-
- 기존 방식은 현재 Map을 통해 조회 결과 값을 처리하고 있습니다. 해당 같은 경우 컴파일 에러 체크가 어려우며, 사용처에 대한 내용이 불투명하여 특정 이슈가 발생 시 문제해결에 어려움이 있을 수 있습니다. 
- 해결방안
- Map 형식이 아닌 명시적인 응답 값(DTO) 설정을 통해 이와 같은 원인을 해결하도록 조치

**Comment by f-lab-elkein** [comment]
https://github.com/f-lab-edu/black-friday/pull/4/commits/72b491b8048f5d9e74c6e41bd69e5a69fe1c42ab#diff-e246991bb7fc4c4af6e5f3cc195c3cc5ceb99ebaf41eb2a76faa050caf933e0f 에서 추가 커밋으로 해결하셨음
